apiVersion: v1
kind: Service
metadata:
  name: app-ui-service
spec:
  selector:
    app: app-ui
  type: LoadBalancer
  ports:
  - port: 8090
    targetPort: 80
    protocol: TCP
    nodePort: 30001
